USE [master]
GO

/****** Object:  Database [Courses]    Script Date: 11/23/2018 8:44:30 PM ******/
CREATE DATABASE [Courses]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Courses', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Courses.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Courses_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Courses_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Courses] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Courses].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Courses] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Courses] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Courses] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Courses] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Courses] SET ARITHABORT OFF 
GO

ALTER DATABASE [Courses] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Courses] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Courses] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Courses] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Courses] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Courses] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Courses] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Courses] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Courses] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Courses] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Courses] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Courses] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Courses] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Courses] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Courses] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Courses] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Courses] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Courses] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Courses] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Courses] SET  MULTI_USER 
GO

ALTER DATABASE [Courses] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Courses] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Courses] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Courses] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Courses] SET  READ_WRITE 
GO


